version: 2
updates:
    # Monorepo root
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
    # Hardhat
    - package-ecosystem: 'npm'
      directory: '/apps/blockchain'
      schedule:
          interval: 'weekly'
    # React w/ Vite
    - package-ecosystem: 'npm'
      directory: '/apps/sample-dapp'
      schedule:
          interval: 'weekly'
    # Next.js
    - package-ecosystem: 'npm'
      directory: '/apps/frontend'
      schedule:
          interval: 'weekly'
