version: 2
updates:
  # Hardhat
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  # React w/ Vite
  - package-ecosystem: "npm"
    directory: "/sample-dapp"
    schedule:
      interval: "weekly"
  # Next.js
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
